# Generated by Django 6.0.1 on 2026-01-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(blank=True, null=True)),
                ('pair', models.CharField(max_length=20, null=True)),
                ('momentum_h4', models.CharField(max_length=20, null=True)),
                ('momentum_h1', models.CharField(max_length=20, null=True)),
                ('momentum_15m', models.CharField(max_length=20, null=True)),
                ('momentum_5m', models.CharField(max_length=20, null=True)),
                ('momentum_1m', models.CharField(max_length=20, null=True)),
                ('session', models.CharField(max_length=20, null=True)),
                ('entry_place', models.CharField(max_length=20, null=True)),
                ('buy_or_sell', models.CharField(max_length=20, null=True)),
                ('setup_quality', models.IntegerField(blank=True, null=True)),
                ('trade_type', models.CharField(max_length=20, null=True)),
                ('confirmation', models.CharField(max_length=20, null=True)),
                ('mood', models.CharField(max_length=20, null=True)),
                ('tp', models.CharField(max_length=20, null=True)),
                ('tp_reason', models.CharField(max_length=20, null=True)),
                ('risk_reward', models.FloatField(blank=True, null=True)),
                ('rvs', models.IntegerField(blank=True, null=True)),
                ('rvs_grade', models.CharField(max_length=20, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(max_length=20, null=True)),
                ('holding_time_hrs', models.IntegerField(blank=True, null=True)),
                ('holding_time_mns', models.IntegerField(blank=True, null=True)),
                ('narration', models.CharField(max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
