# Generated by Django 5.2.10 on 2026-01-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(blank=True, null=True)),
                ('momentum_h4', models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True)),
                ('momentum_h1', models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True)),
                ('momentum_15m', models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True)),
                ('momentum_5m', models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True)),
                ('momentum_1m', models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True)),
                ('session', models.CharField(max_length=20, null=True)),
                ('entry_place', models.CharField(choices=[('key level', 'Key level'), ('POI', 'POI'), ('BRT', 'BRT'), ('Other', 'Other')], max_length=20, null=True)),
                ('buy_or_sell', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=20, null=True)),
                ('setup_quality', models.IntegerField(blank=True, choices=[(5, '5 Stars'), (4, '4 Stars'), (3, '3 Stars'), (2, '2 Stars'), (1, '1 Star')], null=True)),
                ('trade_type', models.CharField(choices=[('Scalping (1M)', 'Scalping (1M)'), ('Day trading (5M)', 'Day trading (5M)'), ('Intraday trading (15M)', 'Intraday trading (15M)'), ('Swing (H1)', 'Swing (H1) ')], max_length=50, null=True)),
                ('confirmation', models.CharField(choices=[('Big maru/pin bar', 'Big maru/pin bar'), ('Triple top', 'Triple top'), ('Double top', 'Double top'), ('No confirmation', 'No confirmation')], max_length=20, null=True)),
                ('mood', models.CharField(choices=[('Calm', 'Calm'), ('FOMO', 'FOMO'), ('Frustrated', 'Frustrated'), ('Tired', 'Tired')], max_length=20, null=True)),
                ('tp', models.CharField(choices=[('Below recent high', 'Below recent high'), ('At recent high', 'At recent high'), ('Above recent high', 'Above recent high')], max_length=20, null=True)),
                ('tp_reason', models.CharField(choices=[(' Everything OK', ' Everything OK'), ('Fake BO at KL', 'Fake BO at KL'), ('Strong opposite KL', 'Strong opposite KL'), ('Strong opposite POIL', 'Strong opposite POI'), ('Strong maru/pin', 'Strong maru/pin (Price rejection)'), ('Double top', 'Double top'), ('Triple top', 'Triple top'), ('Strong opposite volume', 'Strong opposite volume')], max_length=50, null=True)),
                ('risk_reward', models.FloatField(blank=True, null=True)),
                ('rvs', models.IntegerField(blank=True, null=True)),
                ('rvs_grade', models.CharField(max_length=20, null=True)),
                ('target', models.IntegerField(blank=True, choices=[(1, 'Win'), (0, 'Lose')], null=True)),
                ('reason', models.CharField(choices=[('Psycho/Mood', 'Psycho/Mood'), ('Wrong Structure', 'Wrong Structure'), ('Trend', 'Trend'), ('FOMO', 'FOMO'), ('Greed', 'Greed'), ('No Confirmation', 'No Confirmation'), ('Momentum', 'Momentum'), ('News', 'News'), ('Other', 'Other')], max_length=20, null=True)),
                ('holding_time', models.IntegerField(blank=True, null=True)),
                ('narration', models.CharField(max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trade.pairs')),
            ],
        ),
    ]
