# Generated by Django 6.0.1 on 2026-01-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='buy_or_sell',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='confirmation',
            field=models.CharField(choices=[('Big maru/pin bar', 'Big maru/pin bar'), ('Triple top', 'Triple top'), ('Double top', 'Double top'), ('No confirmation', 'No confirmation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='entry_place',
            field=models.CharField(choices=[('key level', 'Key level'), ('POI', 'POI'), ('BRT', 'BRT')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_15m',
            field=models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_1m',
            field=models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_5m',
            field=models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_h1',
            field=models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_h4',
            field=models.CharField(choices=[('Up Strong', 'Up Strong'), ('Down Strong', 'Down Strong'), ('Up Very strong', 'Up Very strong'), ('Down Very strong', 'Down Very strong '), ('Up weak', 'Up weak'), ('Down weak', 'Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='mood',
            field=models.CharField(choices=[('Calm', 'Calm'), ('FOMO', 'FOMO'), ('Frustrated', 'Frustrated'), ('Tired', 'Tired')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='pair',
            field=models.CharField(choices=[('EUR/USD', 'EUR/USD'), ('NZD/USD', 'NZD/USD'), ('AUD/JPY', 'AUD/JPY'), ('GBP/USD', 'GBP/USD'), ('EUR/JPY', 'EUR/JPY')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='setup_quality',
            field=models.CharField(choices=[('5', '5 Stars'), ('4', '4 Stars'), ('3', '3 Stars'), ('2', '2 Stars'), ('1', '1 Star')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='tp',
            field=models.CharField(choices=[('Below recent high', 'Below recent high'), ('At recent high', 'At recent high'), ('Above recent high', 'Above recent high')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='tp_reason',
            field=models.CharField(choices=[(' Everything OK', ' Everything OK'), ('Fake BO at KL', 'Fake BO at KL'), ('Strong opposite KL', 'Strong opposite KL'), ('Strong opposite POIL', 'Strong opposite POI'), ('Strong maru/pin', 'Strong maru/pin (Price rejection)'), ('Double top', 'Double top'), ('Triple top', 'Triple top'), ('Strong opposite volume', 'Strong opposite volume')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='trade_type',
            field=models.CharField(choices=[('Scalping (1M)', 'Scalping (1M)'), ('Day trading (5M)', 'Day trading (5M)'), ('Intraday trading (15M)', 'Intraday trading (15M)'), ('Swing (H1)', 'Swing (H1) ')], max_length=50, null=True),
        ),
    ]
