# Generated by Django 5.2.10 on 2026-03-02 09:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('confident', '😊 Confident'), ('cautious', '🤔 Cautious'), ('neutral', '😐 Neutral'), ('stressed', '😓 Stressed'), ('energetic', '⚡ Energetic'), ('tired', '😴 Tired'), ('focused', '🎯 Focused'), ('anxious', '😰 Anxious')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('trades_count', models.IntegerField(default=0)),
                ('profit_loss', models.FloatField(default=0)),
                ('win_rate', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='advice',
            options={'ordering': ['-is_active', 'usage_count', '-created_at'], 'verbose_name': 'Advice', 'verbose_name_plural': 'Advice'},
        ),
        migrations.RemoveIndex(
            model_name='advice',
            name='trade_advic_usage_c_86db30_idx',
        ),
        migrations.AlterField(
            model_name='trades',
            name='buy_or_sell',
            field=models.CharField(blank=True, choices=[('BUY', '🟢 BUY'), ('SELL', '🔴 SELL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='confirmation',
            field=models.CharField(blank=True, choices=[('Big maru/pin bar', '📌 Big maru/pin bar'), ('Triple top', '🔝🔝🔝 Triple top'), ('Double top', '🔝🔝 Double top'), ('No confirmation', '❌ No confirmation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='entry_place',
            field=models.CharField(blank=True, choices=[('key level', '🎯 Key level'), ('POI', '📍 POI'), ('BRT', '🔄 BRT'), ('Other', '❓ Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_15m',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_1m',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_5m',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_h1',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_h4',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='mood',
            field=models.CharField(blank=True, choices=[('Calm', '😌 Calm'), ('FOMO', '😰 FOMO'), ('Frustrated', '😤 Frustrated'), ('Tired', '😴 Tired')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='reason',
            field=models.CharField(blank=True, choices=[('Psycho/Mood', '🧠 Psycho/Mood'), ('Wrong Structure', '📐 Wrong Structure'), ('Trend', '📈 Trend'), ('FOMO', '🎯 FOMO'), ('Greed', '💰 Greed'), ('No Confirmation', '⏳ No Confirmation'), ('Momentum', '⚡ Momentum'), ('News', '📰 News'), ('Other', '❓ Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='setup_quality',
            field=models.IntegerField(blank=True, choices=[(5, '🌟🌟🌟🌟🌟'), (4, '🌟🌟🌟🌟'), (3, '🌟🌟🌟'), (2, '🌟🌟'), (1, '🌟')], null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='target',
            field=models.IntegerField(blank=True, choices=[(1, '✅ Win 🏆'), (0, '❌ Lose 💔')], null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='tp',
            field=models.CharField(blank=True, choices=[('Below recent high', '⬇️ Below recent high'), ('At recent high', '⚖️ At recent high'), ('Above recent high', '⬆️ Above recent high')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='tp_reason',
            field=models.CharField(blank=True, choices=[('Everything OK', '✅ Everything OK'), ('Fake BO at KL', '🎭 Fake BO at KL'), ('Strong opposite KL', '🛑 Strong opposite KL'), ('Strong opposite POI', '🚧 Strong opposite POI'), ('Strong maru/pin', '📌 Strong maru/pin (Price rejection)'), ('Double top', '🔝🔝 Double top'), ('Triple top', '🔝🔝🔝 Triple top'), ('Strong opposite volume', '📉 Strong opposite volume')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='trade_type',
            field=models.CharField(blank=True, choices=[('Scalping (1M)', '⚡ Scalping (1M)'), ('Day trading (5M)', '📊 Day trading (5M)'), ('Intraday trading (15M)', '📈 Intraday trading (15M)'), ('Swing (H1)', '🔄 Swing (H1)')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='advice',
            index=models.Index(fields=['usage_count'], name='trade_advic_usage_c_08e5d5_idx'),
        ),
        migrations.AlterModelTable(
            name='advice',
            table='trade_advice',
        ),
        migrations.AddField(
            model_name='mood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mood',
            unique_together={('user', 'date')},
        ),
    ]
