# Generated by Django 6.0.1 on 2026-01-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_trades_buy_or_sell_alter_trades_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='setup_quality',
            field=models.IntegerField(blank=True, choices=[(5, '5 Stars'), (4, '4 Stars'), (3, '3 Stars'), (2, '2 Stars'), (1, '1 Star')], null=True),
        ),
    ]
