# Generated by Django 5.2.10 on 2026-03-09 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_advice_user_pairs_user_trades_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_type', models.CharField(choices=[('FTMO', 'FTMO'), ('The5ers', 'The5ers'), ('MY_FOREX_FUNDS', 'My Forex Funds'), ('FUNDED_NEXT', 'Funded Next'), ('OTHER', 'Other')], max_length=50)),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='USD', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funded_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'account_name'],
            },
        ),
    ]
