# Generated by Django 5.2.10 on 2026-03-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_add_mood_model_fixed'),
        ('trade', '0003_alter_trades_setup_quality'),
    ]

    operations = [
    ]
