# Generated by Django 5.2.10 on 2026-03-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_trades_buy_or_sell_alter_trades_confirmation_and_more'),
        ('trade', '0003_add_mood_model_fixed'),
    ]

    operations = [
    ]
