# Generated by Django 6.0.1 on 2026-01-14 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_trades_setup_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='trades',
            name='entry_place',
            field=models.CharField(choices=[('key level', 'Key level'), ('POI', 'POI'), ('BRT', 'BRT'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='reason',
            field=models.CharField(choices=[('Psycho/Mood', 'Psycho/Mood'), ('Wrong Structure', 'Wrong Structure'), ('Trend', 'Trend'), ('FOMO', 'FOMO'), ('Greed', 'Greed'), ('No Confirmation', 'No Confirmation'), ('Momentum', 'Momentum'), ('News', 'News'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='target',
            field=models.IntegerField(blank=True, choices=[(1, 'Win'), (0, 'Lose')], null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='pair',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trade.pairs'),
            preserve_default=False,
        ),
    ]
