# Generated by Django 5.2.10 on 2026-03-09 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_add_funded_account_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trade.fundedaccount'),
        ),
        migrations.AddField(
            model_name='trades',
            name='calculated_lot_size',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trades',
            name='pip_value_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trades',
            name='risk_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='trades',
            name='stop_loss_pips',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
