# Generated by Django 5.2.8 on 2026-01-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_pairs_alter_trades_entry_place_alter_trades_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='holding_time_hrs',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='holding_time_mns',
        ),
        migrations.AddField(
            model_name='trades',
            name='holding_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pairs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trades',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trade.pairs'),
        ),
    ]
