# Generated by Django 5.2.8 on 2026-01-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_remove_trades_holding_time_hrs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairs',
            name='description',
        ),
    ]
