# Generated by Django 5.2.10 on 2026-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_create_default_funded_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.CharField(choices=[('confident', '😊 Confident'), ('cautious', '🤔 Cautious'), ('neutral', '😐 Neutral'), ('stressed', '😓 Stressed'), ('energetic', '⚡ Energetic'), ('tired', '😴 Tired'), ('focused', '🎯 Focused'), ('anxious', '😰 Anxious')], max_length=100),
        ),
        migrations.AlterField(
            model_name='mood',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='buy_or_sell',
            field=models.CharField(blank=True, choices=[('BUY', '🟢 BUY'), ('SELL', '🔴 SELL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='confirmation',
            field=models.CharField(blank=True, choices=[('Big maru/pin bar', '📌 Big maru/pin bar'), ('Triple top', '🔝🔝🔝 Triple top'), ('Double top', '🔝🔝 Double top'), ('No confirmation', '❌ No confirmation')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='entry_place',
            field=models.CharField(blank=True, choices=[('key level', '🎯 Key level'), ('POI', '📍 POI'), ('BRT', '🔄 BRT'), ('Other', '❓ Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_15m',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_1m',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_5m',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_h1',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='momentum_h4',
            field=models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='mood',
            field=models.CharField(blank=True, choices=[('Calm', '😌 Calm'), ('FOMO', '😰 FOMO'), ('Frustrated', '😤 Frustrated'), ('Tired', '😴 Tired')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='reason',
            field=models.CharField(blank=True, choices=[('Psycho/Mood', '🧠 Psycho/Mood'), ('Wrong Structure', '📐 Wrong Structure'), ('Trend', '📈 Trend'), ('FOMO', '🎯 FOMO'), ('Greed', '💰 Greed'), ('No Confirmation', '⏳ No Confirmation'), ('Momentum', '⚡ Momentum'), ('News', '📰 News'), ('Other', '❓ Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='rvs_grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='tp',
            field=models.CharField(blank=True, choices=[('Below recent high', '⬇️ Below recent high'), ('At recent high', '⚖️ At recent high'), ('Above recent high', '⬆️ Above recent high')], max_length=100, null=True),
        ),
    ]
