# Generated by Django 5.2.8 on 2026-01-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_remove_pairs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='holding_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
