# Generated by Django 5.2.10 on 2026-04-23 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_mood_mood_alter_mood_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momentum_h4', models.CharField(blank=True, max_length=100, null=True)),
                ('momentum_h1', models.CharField(blank=True, max_length=100, null=True)),
                ('momentum_15m', models.CharField(blank=True, max_length=100, null=True)),
                ('momentum_5m', models.CharField(blank=True, max_length=100, null=True)),
                ('momentum_1m', models.CharField(blank=True, max_length=100, null=True)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_place', models.CharField(blank=True, max_length=100, null=True)),
                ('buy_or_sell', models.CharField(blank=True, max_length=100, null=True)),
                ('setup_quality', models.IntegerField(blank=True, null=True)),
                ('trade_type', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmation', models.CharField(blank=True, max_length=100, null=True)),
                ('mood', models.CharField(blank=True, max_length=100, null=True)),
                ('tp', models.CharField(blank=True, max_length=100, null=True)),
                ('tp_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('risk_reward', models.FloatField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('initial_seed', 'Initial Seed'), ('aggregated', 'Aggregated from Users'), ('manual', 'Manually Added')], default='initial_seed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.pairs')),
            ],
            options={
                'verbose_name': 'Global Training Data',
                'verbose_name_plural': 'Global Training Data',
                'db_table': 'global_training_data',
            },
        ),
    ]
