# Generated by Django 5.2.8 on 2026-01-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_alter_trades_holding_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='holding_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
