# Generated by Django 5.2.10 on 2026-07-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_globaltrainingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='draft_created_at',
            field=models.DateTimeField(blank=True, help_text='When the draft was first created', null=True),
        ),
        migrations.AddField(
            model_name='trades',
            name='draft_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the draft was last updated', null=True),
        ),
        migrations.AddField(
            model_name='trades',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='True if this trade is saved as a draft'),
        ),
    ]
