# Generated by Django 5.2.10 on 2026-07-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_trades_draft_created_at_trades_draft_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When the trade was closed (journaled)', null=True),
        ),
    ]
