# Generated by Django 5.2.10 on 2026-07-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_trades_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='setup_image',
            field=models.ImageField(blank=True, help_text='Upload a screenshot of your trade setup', null=True, upload_to='trade_setups/'),
        ),
    ]
