# Generated by Django 5.2.10 on 2026-07-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_trades_setup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='setup_image',
            field=models.ImageField(blank=True, help_text='Upload a screenshot of your trade setup', null=True, upload_to='trade_setups/%Y/%m/%d/'),
        ),
    ]
