# Generated by Django 5.2.10 on 2026-03-03 08:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='The advice or motivational quote')),
                ('author', models.CharField(blank=True, help_text='Author of the quote (leave blank if unknown)', max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('motivation', '💪 Motivation'), ('discipline', '🎯 Discipline'), ('psychology', '🧠 Psychology'), ('risk', '⚠️ Risk Management'), ('trading', '📊 Trading Wisdom'), ('mindset', '🌅 Mindset'), ('patience', '⏳ Patience')], help_text='Category of advice', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this advice should be displayed')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this advice was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='How many times this advice has been shown')),
                ('last_shown', models.DateTimeField(blank=True, help_text='When this advice was last displayed', null=True)),
            ],
            options={
                'verbose_name': 'Advice',
                'verbose_name_plural': 'Advice',
                'db_table': 'trade_advice',
                'ordering': ['-is_active', 'usage_count', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='trade_advic_is_acti_a60d1d_idx'), models.Index(fields=['usage_count'], name='trade_advic_usage_c_08e5d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField(blank=True, null=True)),
                ('momentum_h4', models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True)),
                ('momentum_h1', models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True)),
                ('momentum_15m', models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True)),
                ('momentum_5m', models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True)),
                ('momentum_1m', models.CharField(blank=True, choices=[('Up Strong', '🚀 Up Strong'), ('Down Strong', '💥 Down Strong'), ('Up Very strong', '⚡ Up Very strong'), ('Down Very strong', '🌊 Down Very strong'), ('Up weak', '↗️ Up weak'), ('Down weak', '↘️ Down weak')], max_length=20, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('entry_place', models.CharField(blank=True, choices=[('key level', '🎯 Key level'), ('POI', '📍 POI'), ('BRT', '🔄 BRT'), ('Other', '❓ Other')], max_length=20, null=True)),
                ('buy_or_sell', models.CharField(blank=True, choices=[('BUY', '🟢 BUY'), ('SELL', '🔴 SELL')], max_length=20, null=True)),
                ('setup_quality', models.IntegerField(blank=True, choices=[(5, '🌟🌟🌟🌟🌟'), (4, '🌟🌟🌟🌟'), (3, '🌟🌟🌟'), (2, '🌟🌟'), (1, '🌟')], null=True)),
                ('trade_type', models.CharField(blank=True, choices=[('Scalping (1M)', '⚡ Scalping (1M)'), ('Day trading (5M)', '📊 Day trading (5M)'), ('Intraday trading (15M)', '📈 Intraday trading (15M)'), ('Swing (H1)', '🔄 Swing (H1)')], max_length=50, null=True)),
                ('confirmation', models.CharField(blank=True, choices=[('Big maru/pin bar', '📌 Big maru/pin bar'), ('Triple top', '🔝🔝🔝 Triple top'), ('Double top', '🔝🔝 Double top'), ('No confirmation', '❌ No confirmation')], max_length=20, null=True)),
                ('mood', models.CharField(blank=True, choices=[('Calm', '😌 Calm'), ('FOMO', '😰 FOMO'), ('Frustrated', '😤 Frustrated'), ('Tired', '😴 Tired')], max_length=20, null=True)),
                ('tp', models.CharField(blank=True, choices=[('Below recent high', '⬇️ Below recent high'), ('At recent high', '⚖️ At recent high'), ('Above recent high', '⬆️ Above recent high')], max_length=20, null=True)),
                ('tp_reason', models.CharField(blank=True, choices=[('Everything OK', '✅ Everything OK'), ('Fake BO at KL', '🎭 Fake BO at KL'), ('Strong opposite KL', '🛑 Strong opposite KL'), ('Strong opposite POI', '🚧 Strong opposite POI'), ('Strong maru/pin', '📌 Strong maru/pin (Price rejection)'), ('Double top', '🔝🔝 Double top'), ('Triple top', '🔝🔝🔝 Triple top'), ('Strong opposite volume', '📉 Strong opposite volume')], max_length=50, null=True)),
                ('risk_reward', models.FloatField(blank=True, null=True)),
                ('rvs', models.IntegerField(blank=True, null=True)),
                ('rvs_grade', models.CharField(blank=True, max_length=20, null=True)),
                ('target', models.IntegerField(blank=True, choices=[(1, '✅ Win 🏆'), (0, '❌ Lose 💔')], null=True)),
                ('reason', models.CharField(blank=True, choices=[('Psycho/Mood', '🧠 Psycho/Mood'), ('Wrong Structure', '📐 Wrong Structure'), ('Trend', '📈 Trend'), ('FOMO', '🎯 FOMO'), ('Greed', '💰 Greed'), ('No Confirmation', '⏳ No Confirmation'), ('Momentum', '⚡ Momentum'), ('News', '📰 News'), ('Other', '❓ Other')], max_length=20, null=True)),
                ('holding_time', models.IntegerField(blank=True, null=True)),
                ('narration', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trade.pairs')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('confident', '😊 Confident'), ('cautious', '🤔 Cautious'), ('neutral', '😐 Neutral'), ('stressed', '😓 Stressed'), ('energetic', '⚡ Energetic'), ('tired', '😴 Tired'), ('focused', '🎯 Focused'), ('anxious', '😰 Anxious')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('trades_count', models.IntegerField(default=0)),
                ('profit_loss', models.FloatField(default=0)),
                ('win_rate', models.FloatField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
